name: bottom_navigation_2
description: Bottom navigation example app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  beamer:
    path: ../../package
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
